replicaCount: 1

image:
  repository: hashemabusara/creative-test
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  port: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  cpuTargetPercentage: 70
