apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: my-api-service
    helm.sh/chart: my-api-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: my-api-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
